### PR TITLE
For a 0.4.0 release

### PR DESCRIPTION
**Pull request by ablaom**

### CODE REVIEW

**Comment by ablaom** [comment]
Well this is weird. This dev branch is failing but I don't believe I merged a failing PR.

@OkonSamuel Did you perchance push some commits directly to dev? In particular, this commit here did not pass CI:

https://github.com/alan-turing-institute/MLJTuning.jl/commit/5efba644e7cbb74072ac50f543fadc913aa007d3

Ah. It looks like you added 1.4 testing and that's why we have a fail. Any idea what the reason is?

**Comment by OkonSamuel** [comment]
> Any idea what the reason is?

Not really. just wanted to update the tests as the nightlies now point to julia v6

**Comment by OkonSamuel** [comment]
@ablaom. The Concunrency branches fixes it

**Comment by OkonSamuel** [comment]
Also some of the test dependencies are causing builds to go stale (sometimes give EOF error which you mentioned earlier)

**Comment by ablaom** [comment]
@OkonSamuel

 It appears from comments above that #57 (breaking) is required before this one. If so, can you please re-title this PR, reminding me what this PR does (remove dictionaries ?)

**Comment by ablaom** [comment]
Nevermind, I forgot this is already the dev branch. 

I'm going to merge this and #57 and just live with the extra breaking release. I have other updates I want to make here.

**Comment by ablaom** [comment]
@OkonSamuel Good catch, although I should not think a good idea (or good reason?) to have mutating range objects, and could add that to the docs.

**Pull request merged**
